# Generated by Django 6.1 on 2026-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField(help_text='Объём ОЗУ в ГБ')),
                ('storage', models.IntegerField(help_text='Объём SSD в ГБ')),
                ('screen_size', models.DecimalField(decimal_places=1, help_text='Диагональ в дюймах', max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
